services:
  nginx:
    container_name: t.nginx
    image: nginx-test
    hostname: t.nginx
    build: ./nginx
    ports:
      - "3004:80"
    environment:
      - NGINX_PORT=80
    networks:
      - dnet
  
  client:
    container_name: t.client
    image: client-test
    hostname: t.client
    build: ./client
    ports:
      - "3000:80"
    networks:
      - dnet

  backend:
    container_name: t.backend
    image: backend-test
    build: ./backend
    ports:
      - "3003:80"
    networks: 
      - dnet


networks:
  dnet:
    