services:
  nginx:
    container_name: nginx-entry
    build: ./nginx
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
    networks: 
      dnet:


networks:
  dnet:
    name: dnet
    driver: bridge